name: Sync Subdirectory to Target Repo

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  sync-subdirectory:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the source repository
      - name: Checkout Source Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Set up Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      # Step 3: Sync Subdirectory to Target Repo
      - name: Sync Subdirectory
        run: |
          # Define variables
          SUBDIR="src/content" # Path to the subdirectory to sync
          TARGET_REPO="https://${{ secrets.API_TOKEN_GITHUB }}@github.com/jpkha/auto-copy-from-another-repo.git" # Target repository URL
           
          # Clone the target repository
          git clone $TARGET_REPO target-repo
          cd target-repo

          # Copy subdirectory from the source repo
          rsync -av --delete ../$SUBDIR ./

          # Commit and push changes to the target repo
          git add .
          git commit -m "Sync updates from source repository"
          git push origin main

      # Step 4: Clean up
      - name: Clean Up
        run: |
          rm -rf target-repo
